name: IndexNow Submit + Sitemap Update
on:
  push:
    branches: [main]
    paths:
      - '**/*.html'
      - '**/*.htm'
  workflow_dispatch:

jobs:
  submit-and-update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get changed HTML files
        id: changed-files
        run: |
          echo "Finding changed HTML files..."
          git diff --name-only HEAD~1 HEAD | grep -E '\.(html|htm)$' > changed_html.txt || touch changed_html.txt
          
          echo "Finding newly added HTML files..."
          git diff --name-status HEAD~1 HEAD | grep -E '^A.*\.(html|htm)$' | cut -f2 >> changed_html.txt || echo "No new HTML files"
          
          if [ -s changed_html.txt ]; then
            sort changed_html.txt | uniq | sed 's|^|https://contraco.net/|' > urls_to_submit.txt
            echo "URLs to submit to IndexNow:"
            cat urls_to_submit.txt
            echo "found_files=true" >> $GITHUB_OUTPUT
          else
            echo "No HTML files changed"
            echo "found_files=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Generate sitemap.xml
        run: |
          echo "Generating sitemap.xml..."
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          
          # Find all HTML files and add to sitemap
          find . -name "*.html" -not -path "./.git/*" -not -name "404.html" | while read file; do
            # Convert file path to URL
            url=$(echo "$file" | sed 's|^\./||' | sed 's|/index\.html$|/|' | sed 's|^|https://contraco.net/|')
            
            # Get file modification date
            lastmod=$(date -r "$file" +"%Y-%m-%d")
            
            # Add URL to sitemap
            echo "  <url>" >> sitemap.xml
            echo "    <loc>$url</loc>" >> sitemap.xml
            echo "    <lastmod>$lastmod</lastmod>" >> sitemap.xml
            echo "    <changefreq>weekly</changefreq>" >> sitemap.xml
            echo "    <priority>0.8</priority>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done
          
          echo '</urlset>' >> sitemap.xml
          echo "Generated sitemap with $(grep -c "<url>" sitemap.xml) URLs"
      
      - name: Install jq
        if: steps.changed-files.outputs.found_files == 'true'
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Submit to IndexNow
        if: steps.changed-files.outputs.found_files == 'true'
        run: |
          if [ -s urls_to_submit.txt ]; then
            urls_json=$(jq -R -s -c 'split("\n")[:-1]' urls_to_submit.txt)
            
            echo "Submitting to IndexNow API..."
            response=$(curl -s -w "\nHTTP_CODE:%{http_code}" -X POST "https://api.indexnow.org/indexnow" \
              -H "Content-Type: application/json" \
              -d '{
                "host": "contraco.net",
                "key": "${{ secrets.INDEXNOW_KEY }}",
                "keyLocation": "https://contraco.net/${{ secrets.INDEXNOW_KEY }}.txt",
                "urlList": '$urls_json'
              }')
            
            http_code=$(echo "$response" | grep "HTTP_CODE:" | cut -d: -f2)
            
            if [ "$http_code" = "200" ] || [ "$http_code" = "202" ]; then
              echo "✅ Successfully submitted $(wc -l < urls_to_submit.txt) URLs to IndexNow"
            else
              echo "❌ Failed to submit URLs. HTTP Status: $http_code"
              exit 1
            fi
          fi
      

- name: Commit sitemap.xml
  run: |
    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    git add sitemap.xml
    if git diff --staged --quiet; then
      echo "No changes to sitemap.xml"
    else
      git commit -m "Auto-update sitemap.xml"
      git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/contraco/contraco.git
      git push origin main
      echo "✅ Sitemap updated and committed"
    fi

